#!/usr/bin/env python3
"""Seed the pricing basis from a price-book workbook.

Run when a new book arrives:  python3 tests/extract_price_book.py <book.xlsx>

This is a ONE-WAY seed, not a sync. The book is an OUTPUT of the basis — see
calculators/_pricing.py — so this exists to capture option prices MCE has no
other record of (air pan, sanitary design, rock trap and the rest) and to let
`pricing_cli.py check` diff a newly received book against what the basis says it
should be.
"""
import pathlib
import pprint
import sys

import openpyxl

FAMILIES = {"XM 19\" Hammermill": 19, "XM 22\" Hammermill": 22,
            "XM 38\" Hammermill": 38, "XM 44\" Hammermill": 44}
MILL_OPTION_ROWS = {
    "Base Price": "base",
    "Sanitary Design": "sanitary",
    "AR Internal Wear Plates": "ar_plates",
    "Rubber Vibration Pads": "vibration_pads",
    "Drop Down Air Pan": "air_pan",
    "Manual Clean": "magnet_manual",
    "Auto Self Clean": "magnet_auto",
    "Rock Trap": "rock_trap",
    "SF300 Magnet": "sf300_magnet",
}


def cells(row):
    return ["" if c is None else c for c in row]


def number(value):
    """The book stores its figures as text, and some carry commas or a $."""
    if isinstance(value, (int, float)):
        return int(value)
    text = str(value).replace(",", "").replace("$", "").strip()
    try:
        return int(round(float(text)))
    except ValueError:
        return None


def main(path):
    ws = openpyxl.load_workbook(path, data_only=True)["Sheet1"]
    rows = [cells(r) for r in ws.iter_rows(values_only=True)]

    mills, models = {}, []
    for r in rows:
        # the model-row header is a two-line cell: '3/4" Dia.\nHammer Pins'
        head = str(r[0]).strip().splitlines()[-1].strip() if str(r[0]).strip() else ""
        if str(r[0]).strip() in FAMILIES:
            models = []
            continue
        # the feeder tables reuse "Manual Clean" / "Auto Self Clean" for the combo
        # adapter, so the mill scan stops where the feeder section starts or the
        # mill magnet figures get overwritten by the feeder's
        if "FEEDER" in str(r[0]).upper():
            models = []
            continue
        if head in ("Hammer Pins", "Magnet Adapter"):
            models = [str(c).strip() for c in r[1:] if str(c).strip()]
            continue
        key = MILL_OPTION_ROWS.get(head)
        if key and models:
            for model, value in zip(models, r[1:]):
                n = number(value)
                if n is not None:
                    mills.setdefault(model, {})[key] = n
    out = pathlib.Path(__file__).resolve().parent.parent / "calculators" / "_book_inputs.py"
    out.write_text(
        '"""Option prices seeded from MCE\'s hammermill price book.\n\n'
        "Generated by tests/extract_price_book.py — do not hand-edit. These are the\n"
        "book's own figures for options the calculator has no formula for; the basis\n"
        "in _pricing.py escalates them and the book is regenerated from there.\n"
        f'\nSource: {pathlib.Path(path).name}\n"""\n\n'
        "MILL_OPTIONS = " + pprint.pformat(dict(sorted(mills.items())), width=88) + "\n")
    print(f"wrote {out} — {len(mills)} models, "
          f"{sorted({k for v in mills.values() for k in v})}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else sys.exit("usage: extract_price_book.py <xlsx>"))
